import { useState } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
  StyleSheet, KeyboardAvoidingView, Platform, Alert, ScrollView,
} from 'react-native';
import { Link, useRouter } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { colors, spacing, font } from '../../lib/theme';

type Role = 'driver' | 'admin';

export default function RegisterScreen() {
  const router = useRouter();
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [companyName, setCompanyName] = useState('');
  const [joinCode, setJoinCode] = useState('');
  const [role, setRole] = useState<Role>('driver');
  const [loading, setLoading] = useState(false);

  const registerAdmin = async () => {
    // Create auth user (auto-signs in since email confirmation is off)
    const { data: authData, error: authError } = await supabase.auth.signUp({ email, password });
    if (authError || !authData.user) throw new Error(authError?.message ?? 'Sign up failed');

    // Create the company (join_code is auto-generated by the DB)
    const { data: company, error: companyError } = await supabase
      .from('companies')
      .insert({ name: companyName })
      .select('id, join_code')
      .single();
    if (companyError || !company) throw new Error('Could not create company.');

    // Create the admin profile
    const { error: profileError } = await supabase.from('profiles').insert({
      id: authData.user.id,
      full_name: fullName,
      role: 'admin',
      company_id: company.id,
    });
    if (profileError) throw new Error(profileError.message);

    return company.join_code as string;
  };

  const registerDriver = async () => {
    // Resolve the join code -> company id BEFORE creating the account
    const { data: companyId, error: rpcError } = await supabase
      .rpc('join_company_id', { code: joinCode.trim() });
    if (rpcError) throw new Error(rpcError.message);
    if (!companyId) throw new Error('That join code does not match any company.');

    // Create auth user
    const { data: authData, error: authError } = await supabase.auth.signUp({ email, password });
    if (authError || !authData.user) throw new Error(authError?.message ?? 'Sign up failed');

    // Create the driver profile linked to the company
    const { error: profileError } = await supabase.from('profiles').insert({
      id: authData.user.id,
      full_name: fullName,
      role: 'driver',
      company_id: companyId,
    });
    if (profileError) throw new Error(profileError.message);
  };

  const handleRegister = async () => {
    if (!fullName || !email || !password) {
      Alert.alert('Missing fields', 'Please fill in your name, email, and password.');
      return;
    }
    if (role === 'admin' && !companyName) {
      Alert.alert('Missing company', 'Please enter your company name.');
      return;
    }
    if (role === 'driver' && !joinCode) {
      Alert.alert('Missing code', 'Please enter the join code from your admin.');
      return;
    }

    setLoading(true);
    try {
      if (role === 'admin') {
        const code = await registerAdmin();
        Alert.alert(
          'Company created!',
          `Your join code is ${code}\n\nShare it with your drivers so they can register. You can find it again on your dashboard.`,
        );
      } else {
        await registerDriver();
        Alert.alert('Success', 'Account created! You can now sign in.');
      }
      router.replace('/(auth)/login');
    } catch (e: any) {
      Alert.alert('Registration failed', e.message ?? 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView contentContainerStyle={styles.inner} keyboardShouldPersistTaps="handled">
        <Text style={styles.title}>Create Account</Text>

        <Text style={styles.label}>I am a...</Text>
        <View style={styles.roleRow}>
          {(['driver', 'admin'] as Role[]).map((r) => (
            <TouchableOpacity
              key={r}
              style={[styles.roleBtn, role === r && styles.roleBtnActive]}
              onPress={() => setRole(r)}
            >
              <Text style={[styles.roleBtnText, role === r && styles.roleBtnTextActive]}>
                {r === 'driver' ? '🚛 Driver' : '🗂 Admin'}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        <TextInput style={styles.input} placeholder="Full Name" placeholderTextColor={colors.muted}
          value={fullName} onChangeText={setFullName} />
        <TextInput style={styles.input} placeholder="Email" placeholderTextColor={colors.muted}
          value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" />
        <TextInput style={styles.input} placeholder="Password" placeholderTextColor={colors.muted}
          value={password} onChangeText={setPassword} secureTextEntry />

        {role === 'admin' ? (
          <>
            <TextInput style={styles.input} placeholder="Company Name" placeholderTextColor={colors.muted}
              value={companyName} onChangeText={setCompanyName} />
            <Text style={styles.hint}>You'll get a join code to share with your drivers.</Text>
          </>
        ) : (
          <>
            <TextInput
              style={[styles.input, styles.codeInput]}
              placeholder="Join Code"
              placeholderTextColor={colors.muted}
              value={joinCode}
              onChangeText={(t) => setJoinCode(t.toUpperCase())}
              autoCapitalize="characters"
              autoCorrect={false}
            />
            <Text style={styles.hint}>Ask your company admin for the 6-character join code.</Text>
          </>
        )}

        <TouchableOpacity
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={handleRegister}
          disabled={loading}
        >
          <Text style={styles.buttonText}>{loading ? 'Creating...' : 'Create Account'}</Text>
        </TouchableOpacity>

        <Link href="/(auth)/login" style={styles.link}>
          Already have an account? <Text style={styles.linkAccent}>Sign In</Text>
        </Link>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  inner: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.xl },
  title: { fontSize: font.xxl, fontWeight: '700', color: colors.text, marginBottom: spacing.xl },
  input: {
    backgroundColor: colors.card, color: colors.text, borderRadius: 10,
    padding: spacing.md, marginBottom: spacing.md, fontSize: font.md,
    borderWidth: 1, borderColor: colors.border,
  },
  codeInput: { letterSpacing: 4, fontWeight: '700', textAlign: 'center', fontSize: font.lg },
  hint: { color: colors.muted, fontSize: 12, marginTop: -spacing.sm, marginBottom: spacing.md },
  label: { color: colors.muted, fontSize: font.sm, marginBottom: spacing.sm },
  roleRow: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.lg },
  roleBtn: {
    flex: 1, padding: spacing.md, borderRadius: 10, borderWidth: 1,
    borderColor: colors.border, alignItems: 'center', backgroundColor: colors.card,
  },
  roleBtnActive: { borderColor: colors.accent, backgroundColor: colors.accentDark + '33' },
  roleBtnText: { color: colors.muted, fontSize: font.md },
  roleBtnTextActive: { color: colors.accent, fontWeight: '600' },
  button: {
    backgroundColor: colors.accent, borderRadius: 10,
    padding: spacing.md, alignItems: 'center', marginTop: spacing.sm,
  },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { color: '#000', fontWeight: '700', fontSize: font.md },
  link: { marginTop: spacing.lg, textAlign: 'center', color: colors.muted, fontSize: font.sm },
  linkAccent: { color: colors.accent },
});
